In [1]:
# Importing the libraries
import pandas as pd

In [2]:
data_stations = pd.read_csv('data/hubway_stations.csv')
data_trips = pd.read_csv('data/hubway_trips.csv')

In [3]:
data_stations.head()

,id,terminal,station,municipal,lat,lng,status
0,3,B32006,Colleges of the Fenway,Boston,42.340021,-71.100812,Existing
1,4,C32000,Tremont St. at Berkeley St.,Boston,42.345392,-71.069616,Existing
2,5,B32012,Northeastern U / North Parking Lot,Boston,42.341814,-71.090179,Existing
3,6,D32000,Cambridge St. at Joy St.,Boston,42.361285,-71.065140,Existing
4,7,A32000,Fan Pier,Boston,42.353412,-71.044624,Existing

In [4]:
data_trips.head()

,seq_id,hubway_id,status,duration,start_date,strt_statn,end_date,end_statn,bike_nr,subsc_type,zip_code,birth_date,gender
0,1,8,Closed,9,7/28/2011 10:12:00,23.0,7/28/2011 10:12:00,23.0,B00468,Registered,'97217,1976.0,Male
1,2,9,Closed,220,7/28/2011 10:21:00,23.0,7/28/2011 10:25:00,23.0,B00554,Registered,'02215,1966.0,Male
2,3,10,Closed,56,7/28/2011 10:33:00,23.0,7/28/2011 10:34:00,23.0,B00456,Registered,'02108,1943.0,Male
3,4,11,Closed,64,7/28/2011 10:35:00,23.0,7/28/2011 10:36:00,23.0,B00554,Registered,'02116,1981.0,Female
4,5,12,Closed,12,7/28/2011 10:37:00,23.0,7/28/2011 10:37:00,23.0,B00554,Registered,'97214,1983.0,Female

In [12]:
data_trips_copy = data_trips.copy()

In [13]:
agg_train_s2s = data_trips_copy.groupby(['strt_statn', 'end_statn']).agg(['count'])

In [14]:
agg_train_s2s

                     seq_id hubway_id status duration start_date end_date  \
                      count     count  count    count      count    count
strt_statn end_statn
3.0        3.0          472       472    472      472        472      472
           4.0          165       165    165      165        165      165
           5.0          289       289    289      289        289      289
           6.0          100       100    100      100        100      100
           7.0            4         4      4        4          4        4
           8.0           63        63     63       63         63       63
           9.0          102       102    102      102        102      102
           10.0          82        82     82       82         82       82
           11.0         242       242    242      242        242      242
           12.0         529       529    529      529        529      529
           13.0          39        39     39       39         39       39
           14.0         568       568    568      568        568      568
           15.0          17        17     17       17         17       17
           16.0         324       324    324      324        324      324
           17.0          39        39     39       39         39       39
           18.0          21        21     21       21         21       21
           19.0          91        91     91       91         91       91
           20.0          13        13     13       13         13       13
           21.0         439       439    439      439        439      439
           22.0         115       115    115      115        115      115
           23.0           8         8      8        8          8        8
           24.0           8         8      8        8          8        8
           25.0         372       372    372      372        372      372
           26.0         178       178    178      178        178      178
           27.0          97        97     97       97         97       97
           29.0           6         6      6        6          6        6
           30.0         184       184    184      184        184      184
           31.0          10        10     10       10         10       10
           32.0         437       437    437      437        437      437
           33.0         159       159    159      159        159      159
...                     ...       ...    ...      ...        ...      ...
145.0      80.0           1         1      1        1          1        1
           84.0           3         3      3        3          3        3
           87.0           3         3      3        3          3        3
           88.0           5         5      5        5          5        5
           89.0           6         6      6        6          6        6
           90.0           1         1      1        1          1        1
           91.0           5         5      5        5          5        5
           94.0           2         2      2        2          2        2
           95.0           4         4      4        4          4        4
           96.0           2         2      2        2          2        2
           99.0           2         2      2        2          2        2
           113.0          3         3      3        3          3        3
           126.0          1         1      1        1          1        1
           127.0          1         1      1        1          1        1
           128.0          3         3      3        3          3        3
           130.0          4         4      4        4          4        4
           131.0          1         1      1        1          1        1
           132.0          7         7      7        7          7        7
           133.0          1         1      1        1          1        1
           135.0          2         2      2        2          2        2
           136.0          2         2      2        2          2        2
           137.0         14        14     14       14         14       14
           138.0          5         5      5        5          5        5
           139.0          9         9      9        9          9        9
           140.0          3         3      3        3          3        3
           141.0          3         3      3        3          3        3
           142.0          7         7      7        7          7        7
           143.0          5         5      5        5          5        5
           144.0          6         6      6        6          6        6
           145.0          7         7      7        7          7        7

                     bike_nr subsc_type zip_code birth_date gender
                       count      count    count      count  count
strt_statn end_statn
3.0        3.0           472        472      189         77    189
           4.0           165        165      138         64    139
           5.0           288        289      226        107    228
           6.0           100        100       87         43     87
           7.0             4          4        1          0      1
           8.0            63         63       43          8     43
           9.0           102        102       72         26     72
           10.0           82         82       37         20     37
           11.0          242        242      207        118    207
           12.0          529        529      478        198    478
           13.0           39         39       30         30     30
           14.0          568        568      526        139    528
           15.0           17         17       11          9     11
           16.0          324        324      294        202    295
           17.0           39         39       13          7     13
           18.0           21         21       14         11     14
           19.0           91         91       64          7     63
           20.0           13         13        8          4      8
           21.0          439        439      351        124    350
           22.0          115        115      103         53    103
           23.0            8          8        6          6      6
           24.0            8          8        3          2      3
           25.0          372        372      334        195    335
           26.0          178        178      166         86    166
           27.0           97         97       74         26     73
           29.0            6          6        6          2      6
           30.0          184        184      117         47    117
           31.0           10         10        7          5      7
           32.0          436        437      343        153    341
           33.0          159        159       81         56     81
...                      ...        ...      ...        ...    ...
145.0      80.0            1          1        1          0      1
           84.0            3          3        1          0      1
           87.0            3          3        1          0      3
           88.0            5          5        5          0      5
           89.0            6          6        5          0      5
           90.0            1          1        0          0      0
           91.0            5          5        5          0      5
           94.0            2          2        0          0      0
           95.0            4          4        1          0      1
           96.0            2          2        2          0      2
           99.0            2          2        2          0      2
           113.0           3          3        3          0      3
           126.0           1          1        1          0      1
           127.0           1          1        1          0      1
           128.0           3          3        3          0      3
           130.0           4          4        4          0      4
           131.0           1          1        1          0      1
           132.0           7          7        7          0      7
           133.0           1          1        0          0      0
           135.0           2          2        2          0      2
           136.0           2          2        1          0      1
           137.0          14         14       14          0     14
           138.0           5          5        5          0      5
           139.0           9          9        5          0      3
           140.0           3          3        3          0      3
           141.0           3          3        3          0      3
           142.0           7          7        7          0      7
           143.0           5          5        5          0      5
           144.0           6          6        6          0      6
           145.0           7          7        5          0      5

[15233 rows x 11 columns]

In [10]:
agg_train_s2s = grouped_df_train_s2s.agg({'cnt': 'count'})

C:\Users\MAYANK\Anaconda3\lib\site-packages\pandas\core\groupby.py:3961: FutureWarning: using a dict with renaming is deprecated and will be removed in a future version
  return super(DataFrameGroupBy, self).aggregate(arg, *args, **kwargs)

KeyError: 'cnt'

In [9]:
agg_train_s2s

                     seq_id hubway_id status duration start_date end_date  \
                      count     count  count    count      count    count
strt_statn end_statn
3.0        3.0          472       472    472      472        472      472
           4.0          165       165    165      165        165      165
           5.0          289       289    289      289        289      289
           6.0          100       100    100      100        100      100
           7.0            4         4      4        4          4        4
           8.0           63        63     63       63         63       63
           9.0          102       102    102      102        102      102
           10.0          82        82     82       82         82       82
           11.0         242       242    242      242        242      242
           12.0         529       529    529      529        529      529
           13.0          39        39     39       39         39       39
           14.0         568       568    568      568        568      568
           15.0          17        17     17       17         17       17
           16.0         324       324    324      324        324      324
           17.0          39        39     39       39         39       39
           18.0          21        21     21       21         21       21
           19.0          91        91     91       91         91       91
           20.0          13        13     13       13         13       13
           21.0         439       439    439      439        439      439
           22.0         115       115    115      115        115      115
           23.0           8         8      8        8          8        8
           24.0           8         8      8        8          8        8
           25.0         372       372    372      372        372      372
           26.0         178       178    178      178        178      178
           27.0          97        97     97       97         97       97
           29.0           6         6      6        6          6        6
           30.0         184       184    184      184        184      184
           31.0          10        10     10       10         10       10
           32.0         437       437    437      437        437      437
           33.0         159       159    159      159        159      159
...                     ...       ...    ...      ...        ...      ...
145.0      80.0           1         1      1        1          1        1
           84.0           3         3      3        3          3        3
           87.0           3         3      3        3          3        3
           88.0           5         5      5        5          5        5
           89.0           6         6      6        6          6        6
           90.0           1         1      1        1          1        1
           91.0           5         5      5        5          5        5
           94.0           2         2      2        2          2        2
           95.0           4         4      4        4          4        4
           96.0           2         2      2        2          2        2
           99.0           2         2      2        2          2        2
           113.0          3         3      3        3          3        3
           126.0          1         1      1        1          1        1
           127.0          1         1      1        1          1        1
           128.0          3         3      3        3          3        3
           130.0          4         4      4        4          4        4
           131.0          1         1      1        1          1        1
           132.0          7         7      7        7          7        7
           133.0          1         1      1        1          1        1
           135.0          2         2      2        2          2        2
           136.0          2         2      2        2          2        2
           137.0         14        14     14       14         14       14
           138.0          5         5      5        5          5        5
           139.0          9         9      9        9          9        9
           140.0          3         3      3        3          3        3
           141.0          3         3      3        3          3        3
           142.0          7         7      7        7          7        7
           143.0          5         5      5        5          5        5
           144.0          6         6      6        6          6        6
           145.0          7         7      7        7          7        7

                     bike_nr subsc_type zip_code birth_date gender
                       count      count    count      count  count
strt_statn end_statn
3.0        3.0           472        472      189         77    189
           4.0           165        165      138         64    139
           5.0           288        289      226        107    228
           6.0           100        100       87         43     87
           7.0             4          4        1          0      1
           8.0            63         63       43          8     43
           9.0           102        102       72         26     72
           10.0           82         82       37         20     37
           11.0          242        242      207        118    207
           12.0          529        529      478        198    478
           13.0           39         39       30         30     30
           14.0          568        568      526        139    528
           15.0           17         17       11          9     11
           16.0          324        324      294        202    295
           17.0           39         39       13          7     13
           18.0           21         21       14         11     14
           19.0           91         91       64          7     63
           20.0           13         13        8          4      8
           21.0          439        439      351        124    350
           22.0          115        115      103         53    103
           23.0            8          8        6          6      6
           24.0            8          8        3          2      3
           25.0          372        372      334        195    335
           26.0          178        178      166         86    166
           27.0           97         97       74         26     73
           29.0            6          6        6          2      6
           30.0          184        184      117         47    117
           31.0           10         10        7          5      7
           32.0          436        437      343        153    341
           33.0          159        159       81         56     81
...                      ...        ...      ...        ...    ...
145.0      80.0            1          1        1          0      1
           84.0            3          3        1          0      1
           87.0            3          3        1          0      3
           88.0            5          5        5          0      5
           89.0            6          6        5          0      5
           90.0            1          1        0          0      0
           91.0            5          5        5          0      5
           94.0            2          2        0          0      0
           95.0            4          4        1          0      1
           96.0            2          2        2          0      2
           99.0            2          2        2          0      2
           113.0           3          3        3          0      3
           126.0           1          1        1          0      1
           127.0           1          1        1          0      1
           128.0           3          3        3          0      3
           130.0           4          4        4          0      4
           131.0           1          1        1          0      1
           132.0           7          7        7          0      7
           133.0           1          1        0          0      0
           135.0           2          2        2          0      2
           136.0           2          2        1          0      1
           137.0          14         14       14          0     14
           138.0           5          5        5          0      5
           139.0           9          9        5          0      3
           140.0           3          3        3          0      3
           141.0           3          3        3          0      3
           142.0           7          7        7          0      7
           143.0           5          5        5          0      5
           144.0           6          6        6          0      6
           145.0           7          7        5          0      5

[15233 rows x 11 columns]